-- เพิ่ม ProductID ใน order (สำหรับการแสกนบาร์โค้ด/QR ในการแพ็ก)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'order' AND column_name = 'ProductID') THEN
    ALTER TABLE "order" ADD COLUMN "ProductID" text;
  END IF;
END $$;

-- ตารางเก็บข้อมูลการแพ็กสินค้าต่อออเดอร์ (กล่องละแถว)
CREATE TABLE IF NOT EXISTS order_packing (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id text NOT NULL,
  box_index int NOT NULL DEFAULT 1,
  size text NOT NULL,
  weight_kg numeric(10,2) DEFAULT 0,
  items jsonb NOT NULL DEFAULT '[]',
  created_at timestamptz DEFAULT now(),
  UNIQUE(order_id, box_index)
);

COMMENT ON TABLE order_packing IS 'ข้อมูลการแพ็กสินค้าลงกล่องต่อออเดอร์ สำหรับรายงานจัดส่ง';
COMMENT ON COLUMN order_packing.items IS 'Array of { productId, name, qty }';

-- ที่อยู่ผู้รับแยกส่วน (สำหรับรายงานจัดส่ง) ใน order
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'order' AND column_name = 'Subdistrict') THEN
    ALTER TABLE "order" ADD COLUMN "Subdistrict" text;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'order' AND column_name = 'District') THEN
    ALTER TABLE "order" ADD COLUMN "District" text;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'order' AND column_name = 'Province') THEN
    ALTER TABLE "order" ADD COLUMN "Province" text;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'order' AND column_name = 'PostalCode') THEN
    ALTER TABLE "order" ADD COLUMN "PostalCode" text;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'order' AND column_name = 'RecipientPhone') THEN
    ALTER TABLE "order" ADD COLUMN "RecipientPhone" text;
  END IF;
END $$;

-- โปรไฟล์: แยกที่อยู่ (ตำบล อำเภอ จังหวัด รหัสไปรษณีย์) ใน users
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'users' AND column_name = 'Subdistrict') THEN
    ALTER TABLE users ADD COLUMN "Subdistrict" text;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'users' AND column_name = 'District') THEN
    ALTER TABLE users ADD COLUMN "District" text;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'users' AND column_name = 'Province') THEN
    ALTER TABLE users ADD COLUMN "Province" text;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'users' AND column_name = 'PostalCode') THEN
    ALTER TABLE users ADD COLUMN "PostalCode" text;
  END IF;
END $$;
